# Generated by Django 3.1.4 on 2021-07-24 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_name', models.CharField(blank=True, max_length=100)),
                ('groom_name', models.CharField(blank=True, max_length=100)),
                ('wedding_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=225, null=True)),
                ('bride_image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('groom_image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('hero_image_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('hero_image_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('hero_image_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('how_we_met', models.TextField(default='How we met...')),
                ('first_outing', models.TextField(default='First_outing...')),
                ('proposal', models.TextField(default='Tell us about his proposal...')),
                ('courtship', models.TextField(default='Courtship...')),
                ('together_forever', models.TextField(default='Together Forever...')),
                ('gallery_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('gallery_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('gallery_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('gallery_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('gallery_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('gallery_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('wedding_engagement_datetime', models.DateField(blank=True, null=True)),
                ('wedding_engagement_venue', models.CharField(blank=True, max_length=225, null=True)),
                ('wedding_engagement_description', models.TextField(blank=True, default='full description of the wedding engagement', null=True)),
                ('wedding_ceremony_time', models.CharField(blank=True, max_length=225, null=True)),
                ('wedding_ceremony_venue', models.CharField(blank=True, max_length=225, null=True)),
                ('wedding_ceremony_description', models.TextField(blank=True, default='full description of the wedding ceremony...', null=True)),
                ('wedding_reception_time', models.CharField(blank=True, max_length=15, null=True)),
                ('wedding_reception_venue', models.CharField(blank=True, max_length=100, null=True)),
                ('wedding_reception_description', models.TextField(blank=True, default='full description of the wedding reception...', null=True)),
                ('slug', models.SlugField()),
                ('registry', models.BooleanField(default=False, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuestList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('number_of_guest', models.IntegerField()),
                ('attending', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
