# Generated by Django 3.1.4 on 2021-07-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mywebsite',
            name='wedding_engagement_datetime',
        ),
        migrations.AddField(
            model_name='mywebsite',
            name='about_bride',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mywebsite',
            name='about_groom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mywebsite',
            name='wedding_engagement_date',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='mywebsite',
            name='wedding_engagement_time',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='mywebsite',
            name='bride_image',
            field=models.ImageField(blank=True, default='bride_image.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mywebsite',
            name='courtship',
            field=models.TextField(blank=True, default='Courtship...', null=True),
        ),
        migrations.AlterField(
            model_name='mywebsite',
            name='first_outing',
            field=models.TextField(blank=True, default='First_outing...', null=True),
        ),
        migrations.AlterField(
            model_name='mywebsite',
            name='gallery_1',
            field=models.ImageField(blank=True, default='gallery_1.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mywebsite',
            name='gallery_2',
            field=models.ImageField(blank=True, default='gallery_2.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mywebsite',
            name='gallery_3',
            field=models.ImageField(blank=True, default='gallery_3.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mywebsite',
            name='gallery_4',
            field=models.ImageField(blank=True, default='gallery_4.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mywebsite',
            name='gallery_5',
            field=models.ImageField(blank=True, default='gallery_5.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mywebsite',
            name='gallery_6',
            field=models.ImageField(blank=True, default='gallery_6.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mywebsite',
            name='groom_image',
            field=models.ImageField(blank=True, default='groom_image.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mywebsite',
            name='hero_image_1',
            field=models.ImageField(blank=True, default='hero_image_1.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mywebsite',
            name='hero_image_2',
            field=models.ImageField(blank=True, default='hero_image_2.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mywebsite',
            name='hero_image_3',
            field=models.ImageField(blank=True, default='hero_image_3.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mywebsite',
            name='how_we_met',
            field=models.TextField(blank=True, default='How we met...', null=True),
        ),
        migrations.AlterField(
            model_name='mywebsite',
            name='proposal',
            field=models.TextField(blank=True, default='Tell us about his proposal...', null=True),
        ),
        migrations.AlterField(
            model_name='mywebsite',
            name='together_forever',
            field=models.TextField(blank=True, default='Together Forever...', null=True),
        ),
    ]
