# Generated by Django 3.1.4 on 2021-07-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210727_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywebsite',
            name='bride_name',
            field=models.CharField(blank=True, default="bride's name", max_length=100),
        ),
        migrations.AlterField(
            model_name='mywebsite',
            name='groom_name',
            field=models.CharField(blank=True, default="groom's name", max_length=100),
        ),
    ]
