# Generated by Django 3.1.4 on 2021-07-07 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcn', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
