# Generated by Django 3.1.4 on 2021-07-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingprofileinfo',
            name='wedding_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
