# Generated by Django 3.1.4 on 2021-07-08 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210708_0056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeddingProfileInfo',
        ),
    ]
