# Generated by Django 3.1.4 on 2021-07-08 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_delete_weddingprofileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(blank=True, max_length=100)),
                ('user_partner_first_name', models.CharField(blank=True, max_length=100)),
                ('wedding_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=225)),
                ('how_you_heard_about_us', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('date_registered', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
