# Generated by Django 3.1.4 on 2021-07-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_weddingprofileinfo_invite_endlink_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingprofileinfo',
            name='invite_endlink_name',
        ),
        migrations.AlterField(
            model_name='weddingprofileinfo',
            name='slug',
            field=models.SlugField(),
        ),
    ]
