# Generated by Django 3.1.4 on 2021-07-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210708_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingprofileinfo',
            name='registry',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
