# Generated by Django 3.1.4 on 2021-07-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_weddingprofileinfo_registry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeddingProfileInfo',
        ),
    ]
