# Generated by Django 3.1.4 on 2021-07-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/designs/%Y/%m/%d/'),
        ),
    ]
